
base:
  mode: train
  stage_name: asset # asset(stage1) or portfolio(stage2)
  task_name: nikkei # nasdaq ..? 
  model_name: LSTM # LSTM, xgboost
  user_name: sm 
  seed: 813
  data_dir: stage1/data/sm # user_name 
  output_dir: stage1/output/sm # user_name
  

data:
  lookback_window: 10 # 
  lookahead_window: 1 # 
  #feature_list:


train:
  #dataset:
  start_date: 2017-01-01
  end_date: 2020-12-31
  use_derive_vairable: true

  


valid:
  #dataset:
  start_date: 2021-01-01
  end_date: 2021-12-31
  use_derive_vairable: true

test:
  #dataset:
  start_date: 2022-01-01
  end_date: 2022-12-31