
base:
  exp_name: exp_01
  stage_name: asset # asset(stage1) or portfolio(stage2)
  task_name: ind
  index_name: ^BSESN # 
  model_name: LSTM # GRU, LSTM, xgboost
  user_name: jh # 
  seed: 813
  data_dir: stage1/data/jh # user_name 
  output_dir: stage1/output/jh # user_name
  mode: infer

data:
  lookback_window: 50 #  look back period 5 21 42
  lookahead_window: 30 # 62 # 5
  y_form: ratio # value #
  feature_list:
    - Open
    - High
    - Low
    - Close
    - HLmean # H + L / 2
    - OCmean # O + C / 2
    - Volume
    - ATR
    - Parabolic SAR
    - MACD
    - SMA
    - EMA
    - RSI
    - day
    - month
    - dayofweek
    - weekofmonth


test:
  #dataset:
  start_date: 2022-01-01
  end_date: 2022-12-31